### ISSUE TITLE
[feature request] unable to enchant the pickaxe

### ISSUE THREAD

**Issue by mrfloris** [wowkster/BedrockMiner#6]
This is a bit lower of a feature request than some other tickets i've created. But it would be fantastic if we could prevent players from using anvils etc to enchant the pickaxe. We want to kinda provide them with a unique pickaxe and not let them add mending to it to repair it. Making it a lot more rare in the game, forcing players to buy it over and over again.

**Comment by wowkster** [comment]
Will work on this

**Comment by mrfloris** [comment]
Yeah, that would be appreciated. I do not know the tech side for blocking this so I have no suggestions at this point.

The goal for me is to have a unique item that others cannot expand onto, repair, merge with items, rename, etc. It should be a rare item that has limited use, and not something they can easily turn into an infinite usage item.

**Comment by mrfloris** [comment]
Update:

Latest version we're testing has this in the config file
```yaml
# Allow players to apply silk touch in an anvil
allow-anvil-silk: false

# Allow players to add other enchantments through an anvil
allow-anvil-other: false

# Allow players to rename the pickaxe
allow-anvil-rename: false

# Allow players to merge pickaxe with other pickaxes to try and sneak mending/etc on it, or to prevent repair
allow-anvil-merge: false
```
Which is perfect for what we want. I've tested it, working for me as expected.

+1 Done.
