### ISSUE TITLE
[request] Config.yml option for silk touch level requirement

### ISSUE THREAD

**Issue by mrfloris** [wowkster/BedrockMiner#7]
We have silk touch 1 for regular mining, we have silk touch 2 for jobs boosting things, silk touch 3 for another feature and 4 and 5 for certain events and spawner breaking. It would be rather fantastic that we could make it silk touch 6 for bedrock mining. 

Would this please be possible, an option in the config.yml for require silk touch yes, silk touch level: 6.

**Comment by wowkster** [comment]
I will get to adding this add me on discord Wowkster#0969 and we can work out any issues or requests you had

**Comment by wowkster** [comment]
Adding in next release

**Comment by mrfloris** [comment]
Oh that helps us so much! Thank you. Really cool. Thank you again for contacting me on Discord today. It was a productive meeting :) hehe

**Comment by mrfloris** [comment]
Update:

The config file now has a way to set the required silk touch level before dropping, and this is perfect. Meaning we can have one pickaxe for spawners, others for mcMMO double drop, and this one for only bedrock. 

```yaml
#If enabled, drops bedrock blocks if the pickaxe used if enchanted with silk touch
silk-touch: true

# Level silk touch required to obtain bedrock
silk-touch-level: 6
```

+1 Done.
